"""
F&O Stock List — NSE Futures & Options eligible stocks
Updated: Feb 2026. NSE revises this quarterly.
To update: replace the FNO_STOCKS set below.
"""

# Current NSE F&O eligible stocks (~200)
FNO_STOCKS = {
    "AARTIIND","ABB","ABBOTINDIA","ABCAPITAL","ABFRL","ACC","ADANIENT","ADANIGREEN",
    "ADANIPORTS","ALKEM","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP","APOLLOTYRE",
    "ASHOKLEY","ASTRAL","ATUL","AUBANK","AUROPHARMA",
    "AXISBANK","BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BALKRISIND","BANDHANBNK",
    "BANKBARODA","BANKNIFTY","BATAINDIA","BEL","BERGEPAINT","BHARATFORG","BHARTIARTL",
    "BHEL","BIOCON","BOSCHLTD","BPCL","BRITANNIA","BSE","BSOFT",
    "CANBK","CANFINHOME","CHAMBLFERT","CHOLAFIN","CIPLA","COALINDIA","COFORGE",
    "COLPAL","CONCOR","COROMANDEL","CROMPTON","CUB","CUMMINSIND",
    "DABUR","DALBHARAT","DEEPAKNTR","DELTACORP","DEVYANI","DIVISLAB","DIXON",
    "DLF","DMART","DRREDDY",
    "EICHERMOT","ESCORTS","EXIDEIND",
    "FEDERALBNK","GAIL","GLENMARK","GMRINFRA","GNFC","GODREJCP","GODREJPROP",
    "GRANULES","GRASIM","GUJGASLTD",
    "HAL","HAVELLS","HCLTECH","HDFCAMC","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDCOPPER","HINDPETRO","HINDUNILVR","HONAUT",
    "IBULHSGFIN","ICICIBANK","ICICIGI","ICICIPRULI","IDEA","IDFC","IDFCFIRSTB",
    "IEX","IGL","INDHOTEL","INDIAMART","INDIGO","INDUSINDBK","INDUSTOWER",
    "INFY","IOC","IPCALAB","IRCTC","ITC","JINDALSTEL","JKCEMENT","JSL",
    "JSWENERGY","JSWSTEEL","JUBLFOOD",
    "KAJARIACER","KEI","KOTAKBANK","KPITTECH",
    "LALPATHLAB","LAURUSLABS","LICHSGFIN","LT","LTF","LTIM","LTTS","LUPIN",
    "M&M","M&MFIN","MANAPPURAM","MARICO","MARUTI","MCDOWELL-N","MCX",
    "METROPOLIS","MFSL","MGL","MOTHERSON","MPHASIS","MRF","MUTHOOTFIN",
    "NATIONALUM","NAUKRI","NAVINFLUOR","NBCC","NCC","NESTLEIND","NHPC",
    "NMDC","NTPC",
    "OBEROIRLTY","OFSS","OIL","ONGC",
    "PAGEIND","PATANJALI","PEL","PERSISTENT","PETRONET","PFC","PIDILITIND",
    "PIIND","PNB","POLICYBZR","POLYCAB","POWERGRID","PRESTIGE","PVRINOX",
    "RAMCOCEM","RBLBANK","RECLTD","RELIANCE","RVNL",
    "SAIL","SBICARD","SBILIFE","SBIN","SHREECEM","SHRIRAMFIN","SIEMENS",
    "SJVN","SONACOMS","SRF","SUNPHARMA","SUPREMEIND","SYNGENE",
    "TATACHEM","TATACOMM","TATACONSUM","TATAELXSI","TATAMOTORS","TATAPOWER",
    "TATASTEEL","TCS","TECHM","TIINDIA","TITAN","TORNTPHARM","TORNTPOWER",
    "TRENT","TVSMOTOR",
    "UBL","ULTRACEMCO","UNIONBANK","UNITDSPR","UPL",
    "VEDL","VOLTAS",
    "WIPRO",
    "ZOMATO","ZYDUSLIFE",
}


def is_fno(symbol: str) -> bool:
    """Check if a stock is F&O eligible."""
    return symbol.upper() in FNO_STOCKS


def get_fno_tag(symbol: str) -> str:
    """Get display tag for F&O status."""
    return "F&O ✓" if is_fno(symbol) else "Cash"
